# Generated by Django 2.2.2 on 2019-06-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(default='Student', max_length=150)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=50)),
                ('tag_line', models.CharField(default=models.CharField(max_length=50), max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('first_interest', models.CharField(default=None, max_length=50)),
                ('second_interest', models.CharField(default=None, max_length=50)),
                ('third_interest', models.CharField(default=None, max_length=50)),
                ('github_link', models.CharField(max_length=100)),
                ('gitlab_link', models.CharField(max_length=100)),
                ('linkdIn_link', models.CharField(max_length=100)),
                ('full_name', models.ForeignKey(default='Student', on_delete=django.db.models.deletion.CASCADE, to='we_app.Student')),
            ],
        ),
    ]
