# Generated by Django 2.2.2 on 2019-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='Other',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='github_link',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='gitlab_link',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='linkdIn_link',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
