# Generated by Django 2.2.2 on 2019-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0002_auto_20190622_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='fourth_interest',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
