# Generated by Django 2.2.2 on 2019-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0005_auto_20190625_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='full_name',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
