# Generated by Django 2.2.2 on 2019-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0008_auto_20190626_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='faculty_grade',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
