# Generated by Django 2.2.2 on 2019-07-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0013_auto_20190701_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_student',
            old_name='email_id',
            new_name='student_email_id',
        ),
        migrations.RenameField(
            model_name='faculty_student',
            old_name='full_name',
            new_name='student_name',
        ),
    ]
