# Generated by Django 2.2.2 on 2019-07-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0015_fields_of_interets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fields_of_interets',
        ),
    ]
