# Generated by Django 2.2.2 on 2019-06-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0003_student_profile_fourth_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(default='Company', max_length=150)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(default='Faculty', max_length=150)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_name', models.ForeignKey(default='Faculty', on_delete=django.db.models.deletion.CASCADE, to='we_app.Faculty')),
                ('Student_name', models.ForeignKey(default='Student', on_delete=django.db.models.deletion.CASCADE, to='we_app.Student')),
            ],
        ),
    ]
