# Generated by Django 2.2.2 on 2019-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0004_company_faculty_faculty_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='faculty_points',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='faculty_review',
            field=models.CharField(default='Good', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Faculty_Student',
        ),
    ]
