# Generated by Django 2.2.2 on 2019-06-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0007_student_profile_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='email_id',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
