# Generated by Django 2.2.2 on 2019-07-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0012_faculty_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='faculty_grade',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='faculty_points',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='faculty_review',
        ),
    ]
