# Generated by Django 2.2.2 on 2019-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0014_auto_20190701_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields_of_interets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(default='Field', max_length=200)),
            ],
        ),
    ]
