# Generated by Django 2.2.2 on 2019-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_app', '0017_fields_of_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='WE_portal/Resume'),
        ),
    ]
